FROM node:21-alpine AS base
WORKDIR /usr/src/app
COPY package* .
RUN npm install

FROM base AS development
COPY . . 
CMD ["npm", "run", "dev"]

FROM base AS production
COPY . .
RUN npm prune --production
CMD ["npm", "run", "start"]
